stenciljs/output-targets

packages/react-output-target/react-component-lib/utils/attachEventProps.ts
Fixes: https://github.com/ionic-team/stencil-ds-plugins/issues/8
=> Add null check before registering event handlers

package-lock.json, package.json, packages/react-output-target/package.json, packages/react-output-target/react-component-lib/ReactProps.ts, packages/react-output-target/react-component-lib/createComponent.tsx, packages/react-output-target/react-component-lib/createControllerComponent.tsx, packages/react-output-target/react-component-lib/utils/index.tsx, packages/react-output-target/src/output-react.ts
=> fix(react): component types extend React.HTMLAttributes

packages/angular-output-target/package.json, packages/angular-output-target/src/generate-angular-utils.ts, packages/angular-output-target/src/generate-proxies.ts, packages/angular-output-target/src/generate-value-accessors.ts
=> feat(): fix proxies for angular prod builds

packages/react-output-target/react-component-lib/createComponent.tsx
=> fix(react): ReferenceError: document is not defined. 

packages/angular-output-target/src/generate-proxies.ts
See #65 
When components `rootDir` (e.g. core) and `componentCorePackage` (e.g. @ionic/core) have different names the current interface import generates:
`import { Checkbox as ICheckbox } from '../@ionic/core/dist/types/components/my-checkbox/my-checkbox';`
Adjusting the relative import to the `rootDir` will accommodate all cases and generate the right path.
=> fix(#65): adjust relative path with rootDir

packages/example-project/component-library-react/src/react-component-lib/interfaces.ts, packages/react-output-target/react-component-lib/interfaces.ts
=> remove dependency on @stencil/core EventEmitter type for React.

packages/example-project/component-library-react/setupTests.ts, packages/example-project/component-library-react/src/react-component-lib/createComponent.tsx, packages/example-project/component-library-react/tsconfig.json, packages/react-output-target/react-component-lib/createComponent.tsx
=> Ts strict react

.github/workflows/ci.yml
This will ensure issues like #72 do not occur in the future.
=> add test workflow for windows machines.

packages/react-output-target/react-component-lib/createComponent.tsx
Fix #98. Reinstates fix from #40
=> fix(react): ReferenceError: document is not defined.

packages/example-project/component-library-vue/src/vue-component-lib/utils.ts
=> fix(vue-output-target): only access event.detail.value if it's possible

packages/react-output-target/src/output-react.ts
https://github.com/ionic-team/stencil-ds-plugins/issues/49
=> fix(output-react): default loader directory

packages/example-project/component-library-svelte/src/components/MyButton.ts, packages/example-project/component-library-svelte/src/components/MyCheckbox.ts, packages/example-project/component-library-svelte/src/components/MyComponent.ts, packages/example-project/component-library-svelte/src/components/MyInput.ts, packages/example-project/component-library-svelte/src/components/MyPopover.ts, packages/example-project/component-library-svelte/src/components/MyRadio.ts, packages/example-project/component-library-svelte/src/components/MyRadioGroup.ts, packages/example-project/component-library-svelte/src/components/MyRange.ts, packages/svelte-output-target/src/generate-svelte-typings.ts
Messed up the event typing slightly, this should resolve it. Tested everything else, should be no issues from here.
=> fix(svelte): event types should be custom event not detail

packages/example-project/component-library/package.json
Fixes https://github.com/ionic-team/stencil-ds-output-targets/issues/121
=> chore(): resolve failing svelte build

packages/angular-output-target/__tests__/generate-value-accessors.spec.ts, packages/angular-output-target/src/generate-value-accessors.ts
Fixes #165 and adds test case to avoid regressions. Will use this in favor of #166
=> fix(angular): add comm after each host content

packages/angular-output-target/angular-component-lib/utils.ts, packages/angular-output-target/src/generate-angular-directives-file.ts
Add changes that have been made to Angular output files in the Ionic Framework repo
=> style(angular): sync with changes from Framework repo

.github/PULL_REQUEST_TEMPLATE.md
Introduces a pull request template for new PRs.
=> chore(): add pull request template

.github/CODEOWNERS
N/A
Assign multiple owner teams for the repository.
=> chore(CODEOWNERS): multiple global owners

.github/workflows/dev-build.yml, .scripts/bump-version.js, README.md, lerna.json
N/A
Introduces ability to create NPM dev tags for branches.
=> feat(): github action for dev builds

.gitignore, packages/angular-output-target/package.json, packages/react-output-target/package.json, packages/svelte-output-target/package.json, packages/vue-output-target/package.json
Sets-up build related configurations for lerna (attempt 3).
=> chore(): lerna build

package-lock.json, package.json
Issue URL:
- Adds missing semver dep for dev-build workflow
- Removes `publish` command based on it possibly conflicting with the dev-build workflow
=> chore(): remove manual publish command + add semver

.github/workflows/ci.yml, lerna.json, package-lock.json, package.json, packages/angular-output-target/package-lock.json, packages/react-output-target/package-lock.json, packages/svelte-output-target/package-lock.json
N/A
Maintainers can run the "Output Targets Build" Github action to generate dev builds to test branches with.
Successful run: https://github.com/ionic-team/stencil-ds-output-targets/actions/runs/2228011969
=> chore(dev-build): dev build configurations

packages/vue-output-target/package-lock.json, packages/vue-output-target/package.json
=> chore(): release vue 0.6.1

packages/vue-output-target/package-lock.json, packages/vue-output-target/package.json
=> chore(): release vue 0.6.2

packages/vue-output-target/__tests__/generate-vue-components.spec.ts
Issue URL: N/A
this commit fixes vue-based tests that are syntactially incorrect. the
'bug' was originally introduced in 87391cd9. surprisingly, the jest transformer
in this library doesn't appear to throw for this 😬
=> fix(test): syntax errors in vue tests

packages/angular-output-target/__tests__/generate-angular-modules.spec.ts, packages/angular-output-target/__tests__/output-angular.spec.ts, packages/angular-output-target/__tests__/utils.spec.ts, packages/angular-output-target/src/generate-angular-modules.ts, packages/angular-output-target/src/output-angular.ts, packages/angular-output-target/src/types.ts, packages/angular-output-target/src/utils.ts
N/A
- Introduces `createSingleComponentAngularModules ` to output target options to generate Angular modules.
- Generates an Angular module for each component with `createSingleComponentAngularModules ` is `true` and `includeImportCustomElements` is `true`.
- Throws an error if trying to generate Angular modules without the custom elements build.
=> feat(angular): generate scam modules

.github/CODEOWNERS
See "new behavior"
Issue URL: N/A
after changing our infrastructure for maintaining github teams, codeowners is broken for the framework - this commit fixes that with a rename
=> chore(github): fix codeowners for framework

packages/react-output-target/react-component-lib/createComponent.tsx
When compiling the generated `react-component-lib/createComponent.tsx`, developers can receive the following error:
```
@ionic/react:build: src/components/react-component-lib/createComponent.tsx(74,9): error TS2322: Type 'ExpandedPropsTypes' is not assignable to type '{}'.
```
This is because the initial value of the reducer function is `{}` and is not assignable to the `ExpandedPropTypes`.
Note: This is likely derived based on which version of TS you have installed in your project. I only observed the error once experimenting with pnpm, but this is a type error we should resolve in general. 
Issue URL:
- Casts the `ExpandedPropTypes` to the initial value of the reducer
- No …
=> fix(react-output-target): assign ExpandedPropTypes to reducer

lerna.json
=> chore(lerna): remove svelte-output-target from lerna

README.md, package.json, packages/angular-output-target/package.json, packages/example-project/component-library-angular/package.json, packages/example-project/component-library-react/package.json, packages/example-project/component-library-vue/package.json, packages/example-project/component-library/package.json, packages/react-output-target/package.json, packages/vue-output-target/package.json
chore(dev): Adding Volta to the package.json
Volta is the node and npm manager tool that is preferred by most of the Ionic team. This PR adds Volta via the package.json config
There's no Volta version for npm or node specified.
Issue URL:
- Node and npm versions are properly swapped when in development.
=> chore(dev): Adding Volta to the package.json

.github/workflows/actions/publish-npm/action.yml, lerna.json, packages/vue-output-target/package.json
Previously we were manually bumping package versions in each package.json. This should allow lerna to manage the versions as a polyrepo.
Issue URL:
-
-
-
=> chore(release): swapping lerna to use independent mode for versioning.

packages/react-output-target/package-lock.json, packages/react-output-target/package.json
Issue URL:
I incorrectly bumped the package version prior to the release being published. This resulted in 0.5.2 being skipped and 0.5.3 being published. This PR corrects the package version to be in sync with the latest published package.
=> chore(react): manually bumping the package version

packages/angular-output-target/__tests__/generate-angular-component.spec.ts, packages/angular-output-target/src/generate-angular-component.ts, packages/angular-output-target/src/output-angular.ts
Issue URL: Internal
N/A
- Angular output target can generate standalone Angular components when using `outputType: "scam"` and using the custom elements build output from Stencil (specifying a `customElementsDir`).
=> feat(angular-output-target): generate standalone components

packages/angular-output-target/package-lock.json, packages/angular-output-target/package.json
Issue URL: N/A
- Bumps the package version to v0.8.0 
-
-
=> chore(angular-output-target): manually bumping the package version

packages/angular-output-target/src/plugin.ts, packages/angular-output-target/src/types.ts
`outputType: "scam"` is considered experimental. 
Issue URL: Internal
- Single component angular module output type is considered public API
- Removed the experimental warning when using `outputType: "scam"`
=> feat(angular-output-target): SCAM output type is public API

.github/ISSUE_TEMPLATE/bug_report.yml, .github/PULL_REQUEST_TEMPLATE.md, README.md
Issue URL:
this commit updates the maintenance status of the project across the README, issue template, and pull request template
feel free to push back on the verbiage!
=> chore(repo): update maintenance status

packages/vue-output-target/package-lock.json, packages/vue-output-target/package.json
=> chore: bump vue package version

README.md
I made a typo when I updated our README for the current _Maintenance_ status of the repo
Issue URL: N/A
- Typo fixed
=> chore(readme): fix typo in 'Maintenance'

packages/angular-output-target/package-lock.json, packages/angular-output-target/package.json
Issue URL:
This retro-actively bumps the package version from our release ~3 months ago. This will unblock our release workflow.
=> chore(angular): bump package version

.github/workflows/actions/publish-npm/action.yml
Issue URL: N/A
When migrating to pnpm for our production release process, the versioning of packages with lerna broke in the CI environment. This is due to pnpm preventing updates the lockfiles when the `CI` environment flag is set. 
- Force publishes the lerna version updates
- Production release workflow should bump packages as we expect
=> chore(ci): force version bumps in release process

lerna.json, packages/example-project/component-library-vue/package.json, pnpm-lock.yaml
Our lerna configuration is missing configurations expected with pnpm based on the public documentation: https://lerna.js.org/docs/recipes/using-pnpm-with-lerna
Issue URL: N/A
- Assigns pnpm as the npm client for lerna
- Re-generates the lockfile
- Pins the Vue version because they continue to not respect semantic version and push breaking changes to types like it is their job. We can later figure out why they decided to do it again for the `ToggleEvent` type.
=> chore(lerna): configure with pnpm

packages/react-output-target/package.json
=> chore(react): bump package version

packages/angular-output-target/__tests__/generate-angular-component.spec.ts, packages/angular-output-target/src/generate-angular-component.ts
Issue URL:
- enables event names with forward slash
-
-
=> fix(angular): enable event names with forward slash

packages/react-output-target/src/react/ssr.tsx
Light DOM wasn't stringified correctly causing SSR rendering issues.
Improve the rendering of Light DOM.
n/a
=> fix(react): React SSR improvements

packages/vue/src/runtime.ts
This fixes issues we have updating Ionic Framework with the latest Vue Output Target.
=> fix(vue): properly set ROUTER_LINK_VALUE
