README.md

Noticed that the readme still imports wrong NPM packages in the code examples. This pull request fixes that.

Updates the readme to show correct package imports

---

packages/react-output-target/react-component-lib/createComponent.tsx

Dear Ionic team!
I'm really amazed by you StencilJS and this `react-output-target` helper! But it seems that it misses some important bit. A generated component doesn't pass down `data-` and `aria-` attributes.
It would be great if you'll take a look on this PR.
Thank you 🙏

fix(react): pass data- and aria-attributes to React component (#25)

---

packages/react-output-target/__tests__/generate-react-components.spec.ts
packages/react-output-target/package.json
packages/react-output-target/src/output-react.ts
packages/react-output-target/src/plugin.ts
packages/react-output-target/src/types.ts
packages/vue-output-target/__tests__/generate-vue-compontes.spec.ts
packages/vue-output-target/package.json
packages/vue-output-target/src/output-vue.ts
packages/vue-output-target/src/plugin.ts
packages/vue-output-target/src/types.ts

This PR adds more functionality to the React and Vue output targets. You will be able to turn on and off polyfills and defineCustomElements based on stencil.config.ts settings.

Add ability to skip polyfills and registration.

---

packages/angular-output-target/resources/control-value-accessors/value-accessor.ts
packages/example-project/component-library-angular/__tests__/my-input.spec.ts
packages/example-project/component-library-angular/src/directives/proxies.ts
packages/example-project/component-library-angular/src/directives/value-accessor.ts

The base ValueAccessor for the angular-output-target did not implement [setDisabledState](https://angular.io/api/forms/ControlValueAccessor#setDisabledState). This meant that `disabled` prop of components could not be set/managed through `FormControl`s.
By adding setDisabledState, this will now work:
`app.component.ts`:
```ts
import { Component } from "@angular/core";
import { FormBuilder } from "@angular/forms";
@Component({
selector: "app-root",
templateUrl: "./app.component.html",
styleUrls: ["./app.component.css"],
})
export class AppComponent {
form = this.formBuilder.group({
// disabled state will be managed for us by angular
// and now we can later call `this.form.controls.firstName.enable()`
firstName: this.formBuilder.control({ value: "", disabled: true }),
lastName: "",
}); …
```

feat(angular-output-target): implement setDisabledState in ValueAccessor

---

README.md

Based on my work this week with StencilJS and the stencil-ds-ouput-targets repository. I would like to suggest some extra documentation to clarify some small things. Feel free to add remarks/corrections on my writing.
As a next PR I would like to add an example with the my-component component for Angular. If that's OK, please let me know.

docs(general): Added section on how to initiate and use example packages

---

packages/angular-output-target/package.json

As discussed on slack, `@stencil/angular-output-target@0.0.4` is missing the `angular-component-lib` folder, which is required to build the output. This PR adds `angular-component-lib` to the `files` field of the package.json

add angular-component-lib to published package

---

packages/react-output-target/react-component-lib/createComponent.tsx

Thanks for the awesome library. I'm currently exploring the use of Stencil.js for a framework-agnostic Design System. I discovered this issue when testing Stencil.js with `react-output-target` and Next.js using SSR.
Stencil.js works great for SSR, but the `react-output-target` package misbehaves.
Given this Stencil component
```jsx
import { Component, h, Prop } from '@stencil/core';
@Component({
tag: 'my-burger'
})
export class MyBurger {
@Prop() cheese: string = '';
render() {
const cheeseClass = this.cheese ? ` burger--${this.cheese}-cheese` : '';
return (
<div class={'burger' + cheeseClass}>
<slot />
</div>
);
}
}
```
And this React markup
```jsx
<MyBurger cheese="american">
Patty
</MyBurger> 
```
Stencil.js `renderToString()` should produce
```html
<my-burger cheese="american">
<div …
```

fix(react-output-target): render React props in initial render for SSR

---

packages/angular-output-target/resources/control-value-accessors/value-accessor.ts

Build of component-library-angular is failing with angular 10. This PR fixes it by adding Empty Directive Decorator to value-accessor.ts.

Added Empty Directive Decorator

---

packages/vue-output-target/vue-component-lib/utils.ts

See https://github.com/ionic-team/ionic-framework/issues/23539 for more context. In Vue 3.1 there was a breaking change where all properties are now being included in the `props` object even if certain props were not set by the user. These unused props have a value of `undefined`.
With Custom Elements, this causes issues as certain internal values such as event emitters are set on the web component instance resulting in them getting wiped out due to this Vue 3.1 behavior.
This PR fixes the issue by setting the default value of all props to be a `Symbol` so that we can check if the value of a property was not set while respecting properties that can accept `undefined` as a value.

fix(vue): only props set by user are passed to web component

---

packages/angular-output-target/__tests__/output-angular.spec.ts
packages/angular-output-target/src/generate-angular-component.ts
packages/angular-output-target/src/output-angular.ts
packages/angular-output-target/src/utils.ts

* use outputs' complexType definition to detect the output type
* replace className[attribute] value for outputs with Angular's EventEmitter: EvenEmitter<CustomEvent<T>>
The objective is to set the expected output type on each generated proxy component, as the method generateProxyOutputs replaces the original signature by an EventEmitter.
This should fix https://github.com/ionic-team/stencil-ds-output-targets/issues/155

feat(angular): use Angular's EventEmitter with correct type in generated proxy components

---

packages/angular-output-target/angular-component-lib/utils.ts
packages/angular-output-target/package-lock.json
packages/angular-output-target/package.json
packages/angular-output-target/src/generate-angular-component.ts
packages/angular-output-target/src/output-angular.ts
packages/react-output-target/__tests__/generate-react-components.spec.ts
packages/react-output-target/package-lock.json
packages/react-output-target/package.json
packages/react-output-target/react-component-lib/createComponent.tsx
packages/react-output-target/src/output-react.ts
packages/svelte-output-target/package-lock.json
packages/svelte-output-target/package.json
packages/vue-output-target/__tests__/generate-vue-components.spec.ts
packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json
packages/vue-output-target/src/generate-vue-component.ts
packages/vue-output-target/src/output-vue.ts
packages/vue-output-target/vue-component-lib/utils.ts

resolves https://github.com/ionic-team/stencil-ds-output-targets/issues/199
When using `autoDefineCustomElements`, Stencil automatically generates a `defineCustomElement()` call in the body of a component file. This is a side effect, which causes bundlers to pull in the entire file when building. When importing components from a single entry point (I.e. `import { IonButton } from '@ionic/vue';`), this causes bundlers to bundle every component with your application, regardless of whether or not the user is actually using the component in their application.
For example, the entry point of @ionic/vue looks something like this:
**index.esm.js**
```js
import { IonAvatar as IonAvatar$1 } from '@ionic/core/component/ion-avatar.js';
import { IonBadge as IonBadge$1 } from …
```

fix(angular, react, vue): use defineCustomElement import to improve treeshaking

---

packages/react-output-target/react-component-lib/createComponent.tsx

Using `React.createElement` causes Vite to render all components in a Stencil app as `<tagname>` rather than the actual Web Component. See original Ionic issue: https://github.com/ionic-team/ionic-framework/issues/24229
I have identified this to be a Vite bug. See Vite issue: https://github.com/vitejs/vite/issues/6104
According to https://github.com/vitejs/vite/issues/6104#issuecomment-999050698, using the `createElement` named import instead of `React.createElement` fixes the issue. I have verified that this does indeed fix the issue.
I propose we merge this PR in order to get developers unstuck.

fix(react): use createElement named import for better compatibility with Vite

---

packages/react-output-target/__tests__/generate-react-components.spec.ts
packages/react-output-target/src/output-react.ts
packages/react-output-target/src/plugin.ts
packages/react-output-target/src/types.ts
packages/react-output-target/src/utils.ts

this commit adds function-level jsdoc to the react output
wrapper/target. this was done in as a part of an effort to come up to
speed/help others in the same vain.
some type narrowing was performed here, largely to make certain array
types readonly. a conscious decision was made to not make the public
facing api (exposed by src/index.ts) use a ReadonlyArray<T>, so as to
avoid a breaking change (although this may be revisisted in the future)
note that prettier/formatting does not exist in the project today. to avoid
churn now and in the future, I only touched JSDoc to wrap it at 120 lines.
code formatting will come at a later time

chore(react): add function-level jsdoc

---

.github/workflows/ci.yml

there are 2 commits in this PR, that I'll likely rebase + merge (rather than squash) to keep them distinct:
1. https://github.com/ionic-team/stencil-ds-output-targets/pull/225/commits/db283849ab6c1d646190d30b20a302ddee1f4212 - this commit will run CI on pull requests (the enforcement needs to be enabled in github after this lands). it also renames the workflow to
match the stencil core repository
The contents of this PR almost exactly matches that found in the [Stencil core CI setup](https://github.com/ionic-team/stencil/blob/1c1500413a9fa6f7be4ec34f78132c2c670680f3/.github/workflows/main.yml#L1-L10), the only difference being branch names
2. https://github.com/ionic-team/stencil-ds-output-targets/pull/225/commits/22b0517c2bc0f0fb2ae82890ac2063919415619b - remove the duplication between …

chore(github): update ci to run on pull requests

---

.github/workflows/ci.yml
README.md

'master' has been renamed to 'main' via github. this pr updates all
refereces to 'master' in the code

chore(github): rename primary branch from master to main

---

.gitignore

changes to .idea/ could be picked up by np otherwise, blocking a
publish. we don't want to encourage flags to bypass this check, so let's
just add it now to the .gitignore and be done with it

chore(git): add .idea/ to .gitignore

---

.github/CODEOWNERS

Introduces global codeowners for the repository.
When a new PR is opened, both the Framework and Stencil team will be automatically added for review.

chore(): add codeowners

---

.github/CODEOWNERS

The format for the codeowners file is not registering global owners correctly. The VSCode formatting on markdown contents reformatted `*` to `-` during my previous PR.

chore(): codeowners format

---

.github/ionic-issue-bot.yml

Adds the Ionitron (ionic issue bot) to the repository to aid with repository management.

chore(): add ionic issue bot

---

packages/vue-output-target/vue-component-lib/utils.ts

Issue URL: See https://github.com/ionic-team/ionic-framework/issues/25485
In Vue 3.0.0, prop types defaulted to `any`. In Vue 3.0.1 they defaulted to `{}`. https://github.com/vuejs/core/commit/6aa2256913bfd097500aba83b78482b87107c101
Ionic recently updated dev deps to build with Vue 3.2.x (previously, we were using Vue 3.0.0).
This uncovered an issue where all component props had incorrect types: 
```typescript
export declare const IonLabel: import("vue").DefineComponent<JSX.IonLabel & import("./vue-component-lib/utils").InputProps, object, {}, import("vue").ComputedOptions, import("vue").MethodOptions, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, …
```

fix(vue): add correct InputProp types

---

packages/vue-output-target/vue-component-lib/utils.ts

The accepted type signature of `v-model` is hard set to `string | boolean | undefined`. This types is not configurable in the implementation and does not support components that allow a number to be assigned to `v-model`. 
Issue URL: https://github.com/ionic-team/ionic-framework/issues/25575
- Updates the default type signature of `v-model` to be `string | number | boolean | undefined`
- Updates the `defineContainer` function to accept a type to use as the `v-model` type (future work is to make the framework wrappers use the type of `value` from the web component as the type signature)
Dev-build: `0.6.1-dev.11657573317.16e0205c`

fix(vue): update v-model type and allow for custom type signature

---

packages/angular-output-target/__tests__/plugin.spec.ts
packages/angular-output-target/src/generate-angular-directives-file.ts
packages/angular-output-target/src/generate-value-accessors.ts
packages/angular-output-target/src/output-angular.ts
packages/angular-output-target/src/plugin.ts
packages/angular-output-target/src/types.ts

N/A - adding the initial API changes for supporting SCAM modules in the Angular output target.
Issue URL: Internal
- Introduces `proxyDeclarationFile` to the Angular output target config API
- Deprecates `directivesProxyFile` (usage will fallback to this property, if set)
Due to the type change on the `OutputTargetAngular`, `directivesProxyFile` is now optional (up until it is removed) and the new `proxyDeclarationFile` is required. 
Once the SCAM feature is released, developers will need to migrate their stencil config from using `directivesProxyFile` to using the `proxyDeclarationFile` property. Otherwise they will receive a build error when TSC compiles the …

feat(angular): proxyDeclarationFile to generate proxies file

---

packages/angular-output-target/__tests__/generate-angular-component.spec.ts
packages/angular-output-target/src/generate-angular-component.ts

Kebab-case event names do not generate proxies correctly. 
Issue URL: #212
- Kebab-case event names are escaped, allowing the angular output target to correctly generate the component proxies.

fix(angular-output-target): escape kebab-case event names

---

packages/vue-output-target/vue-component-lib/utils.ts

Stencil components that reflect aria attributes from the host, do not work when wrapped in a Vue component.
Issue URL: https://github.com/ionic-team/ionic-framework/issues/26538
- Vue component wrappers will reflect aria attributes from the Vue component host to the Stencil component host

fix(vue): reflect aria attributes to host

---

package-lock.json
package.json
packages/angular-output-target/package-lock.json
packages/angular-output-target/package.json
packages/example-project/component-library-vue/package-lock.json
packages/example-project/component-library/package-lock.json
packages/react-output-target/package-lock.json
packages/react-output-target/package.json
packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json

Issue URL:
This change updates the semver ranges for the `@stencil/core` peer dependency for various framework wrapper packages. This should let us use them with stencil v3.
I think this all works, but to be honest I am not the biggest expert on this repo.
Here's what I did to check that it's working.
First we need to build and package test versions of the framework wrapper packages which have the new version.
This will bootstrap the repo, run build in all the packages, and then run `npm pack` and `npm link` in each of them (I'm not super familiar with lerna so very probably there is a better way to do this!):
```sh
npm run bootstrap
npm run build
npx lerna exec npm pack
npx …
```

chore(deps): update semver ranges for @stencil/core package

---

packages/vue-output-target/__tests__/generate-vue-components.spec.ts
packages/vue-output-target/src/generate-vue-component.ts
packages/vue-output-target/vue-component-lib/utils.ts

Issue URL: see https://github.com/ionic-team/ionic-framework/issues/27057
The Vue framework wrappers assume the prop for components with v-model support have a type of `string | number | boolean`: https://github.com/ionic-team/stencil-ds-output-targets/blob/caa473216ccdc13ee988831ebe65ec62bbbcbfaa/packages/vue-output-target/vue-component-lib/utils.ts#L57
This is not always true as the `ion-select` value prop has a type of `any | null`: https://github.com/ionic-team/ionic-framework/blob/4b822eac5df9e5caa09d56cd1603486996d41429/core/src/components/select/select.tsx#L112
This is causing a TypeScript error when developers pass an object to the `value` prop on `ion-select` since it …

fix(vue): add correct v-model type

---

packages/vue-output-target/vue-component-lib/utils.ts

Generated Vue component wrappers display as `AnonymousComponent` in Vue dev tools.
Issue URL: resolves #143
Generated Vue component wrappers will correctly display as their pascal case component name in dev tools.
|Before|After|
|---|---|
|<img src="https://user-images.githubusercontent.com/13732623/165374824-3ab58df8-266f-45e1-a720-bda365551e97.png" />| <img src="https://user-images.githubusercontent.com/13732623/165374831-4b36cc98-46e8-4824-883f-683d0c4a12c3.png" /> |
This PR is in favor of #162.

fix(vue): apply vue component name to wrapper

---

.github/ionic-issue-bot.yml

Ionitron does not close "stale" issues
Issue URL: N/A
this commit updates the ionitron configuration for the repo by:
1. removing `noReproduction`, as there's no code in ionitron to handle
this block
2. adding a `stale` configuration, to clore issues that are inactive
(14 days) and are not labeled
the labels here were chosen to ensure:
- currently labeled issues do not get immediately closed (they reflect
the current state of the repo)
- labels we plan on continuing to use in the long term are added (e.g.
`package: angular`)
- there are no conflicts with pre-existing rules in the ionitron config
I have pre-emptively added "triage" to some ~22 issues that were unlabeled to …

chore(repo): add stale settings to ionitron config

---

packages/angular-output-target/__tests__/output-angular.spec.ts
packages/angular-output-target/src/output-angular.ts

It will always add `EventEmitter` and `proxyOutputs` imports event if there are no components with event.
Issue URL: Resolves #331
Include import `EventEmitter` and `proxyOutputs` only if there is at least one component with event.

feat(angular): omit output related imports for components with no event

---

packages/vue-output-target/vue-component-lib/utils.ts

Vue 3.3 added support for generic component types and changed the return type of `defineComponent` significantly. It's now always a function.
Since the vue-component-lib is simply moved into the user's library without preprocessing, it has to support the full range of Vue versions supported by Stencil.
Properly fixing the Vue runtime code (Container.name = 'whatever') conditionally *without breaking the type inference* is hard.
It's much easier for us and safer for Volar for us to disable typechecking and let the type inference do its job.
By removing `props: any`, Volar now infers props via inferred return types and we have TypeScript support for Vue.
1. Vue 3.3 doesn't …

fix(vue): Fix typechecking in library code for the Vue output target.

---

packages/angular-output-target/package-lock.json
packages/angular-output-target/package.json
packages/react-output-target/package-lock.json
packages/react-output-target/package.json
packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json

* Both the >= 4.0.0-beta.0 >= 4.0.0 are needed, due to the way that npm interprets pre-release versions
* We will remove/clean-up the pre-release acceptance after v4 of Stencil is released
Issue URL: [STENCIL-810](https://ionic-cloud.atlassian.net/browse/STENCIL-810)
- Supports peerDependencies for Stencil correctly
[STENCIL-810]: https://ionic-cloud.atlassian.net/browse/STENCIL-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(peerDeps): bumping the @stencil/core required peerDep for v4 launch

---

packages/angular-output-target/package-lock.json
packages/angular-output-target/package.json
packages/react-output-target/package-lock.json
packages/react-output-target/package.json
packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json

PRs like this are necessary until we have a bot committing back onto main after a successful production release.

chore(npm): manually bumping the package versions

---

lerna.json
packages/react-output-target/react-component-lib/utils/attachProps.ts

Generated React component wrappers will not fire the `dblclick` event when `onDoubleClick` is bound to the wrapper.
e.g.:
```tsx
<MyComponent onDoubleClick={() => alert('Hello world')}>Click me</MyComponent>
```
Issue URL: Relates to: https://github.com/ionic-team/ionic-framework/issues/21320
- Transforms `doubleclick` naming syntax from React to the browser event `dblclick`
- Creates a utility that can be consumed in a developers projects where they manually generate wrappers (e.g. Ionic Framework generates manual wrappers for routing elements)
Dev-build: `0.5.1-dev.11685564559.1b0b6e89`
Ionic Framework dev-build: `7.0.11-dev.11685565959.10c33d71`

fix(react): component wrappers work with onDoubleClick

---

.github/workflows/actions/publish-npm/action.yml
.github/workflows/prod-build.yml

Issue URL: N/A
The publish npm workflow step uses Lerna 7 instead of the locally installed version.
- The composite action for publishing to npm uses the locally installed version of npm.
-
-

chore: publish-npm workflow uses local lerna version

---

packages/angular-output-target/src/plugin.ts

When referencing multiple instances of the Angular output target in your Stencil project, it will only generate the last instance of the output target. 
Due to invalid global state caching, the last executed validate step will be used for all generate steps of the output target. This is not desired and prevents using multiple instances of an output target.
Issue URL: N/A
- Block-scope cache the validated output target across the validate and generator steps - does not cache across output target.
- Developers can use multiple instances of the same output target in their projects.

fix(angular-output-target): multiple targets do not overwrite each other

---

lerna.json
packages/angular-output-target/__tests__/generate-angular-component.spec.ts
packages/angular-output-target/src/generate-angular-component.ts

Issue URL: Resolves #369
Nested generic types in custom events do not get rewritten correctly within the angular output target. Currently it will output something similar to:
```ts
CustomEvent<IMyComponentIMyComponentMyEvent<[object Object]>>
```
- Angular output target replaces nested generic types within custom events
Dev-build: `@stencil/angular-output-target@0.7.2-dev.11691686917.1045ccb9`

fix(angular-output-target): rewrite nested generics for custom events

---

packages/vue-output-target/README.md
packages/vue-output-target/__tests__/generate-vue-components.spec.ts
packages/vue-output-target/src/generate-vue-component.ts
packages/vue-output-target/src/types.ts
packages/vue-output-target/vue-component-lib/utils.ts

Issue URL: Part of https://github.com/ionic-team/ionic-framework/issues/27292
[Try a reproduction of this issue](https://play.vuejs.org/#eNqdVk1v2zgQ/SuEsIDkwJYO3ZNrB9lms9gu2m7RBslFh8rS2FYrkVySchIY/u87HOqDkt2iqA+GRM7Xe5x51DH4Q8r40ECwDFY6V6U0TINp5HXKy1oKZdiRoclbLhvDTmyrRM3COOmWwteenYJtb4Ih7V7Kc8G1YaU1fsiqBtja2kVhOPO2Bb9ttBG1S7NmERxmbH3NjilnzJqICuJK7KLwE+agOOHcCxof7L+NeLJBV4mDgiDwxUAtq8wAvjG26sEcFrUooFqnwRAnDdhNTpXQGu6NKot+gwNwM0uD61VPAYZdJV6OYB44RhZ1JuOvWnDkloBgJtrQabB00OwaMmXf02BvjNTLJMkLjm5YWnlQMQeTcFknN2iWqIabsoZFIeqbV/Gr+PekKLXxl2PQ9WKjxJMGhUHSYO6lSXDxAGqhgBegQP1s2ombn3qydZbeZscjOSEpRuNBbsvdhJJc1LKsQP0rTYkHPaImqyrx9A+tGdVAjyXfQ/7twvpX/ewwfVRAlXn4TaZ2YNz23ecP8IzP/SZ2QlO1x/CdzU …

fix(vue): ensure v-model is updated before event callback

---

packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json

According to https://github.com/ionic-team/stencil-ds-output-targets/pull/352, we need to bump the package.json after a package has been released.
- Bumps the Vue package.json after the https://github.com/ionic-team/stencil-ds-output-targets/actions/runs/6667732913 release

chore: bump vue output target

---

packages/angular-output-target/__tests__/generate-angular-component.spec.ts
packages/angular-output-target/src/generate-angular-component.ts

When adding a custom event with an inline type:
```
@Event() ionSwipe!: EventEmitter<{ side: Side }>;
```
The generated event type is invalid:
```
ionSwipe: EventEmitter<CustomEvent<IIonItemOptions{ side: IIonItemOptionsSide }>>;
```
There are two issues:
1. The nested type argument is formatted incorrectly (missing <).
2. The evaluated type shouldn’t include `IIonItemOptions`.
Expected output is:
```
ionSwipe: EventEmitter<CustomEvent<{ side: IIonItemOptionsSide }>>;
```
Issue URL: N/A
- The generated event type will account for inline-types.
Dev-build: `0.0.1-dev.11705624885.1949250b`

fix(angular): generate event type with inline types

---

packages/vue-output-target/vue-component-lib/utils.ts

Issue URL: resolves #424
- The Vue wrappers only update the v-model on an element when the event originated from that element and not from any descendant elements.
Dev build: `0.0.1-dev.11711372539.10de27e3`
Verified this issue is fixed using an Ionic Framework build in the sample app from the linked issue.

fix(vue): v-model does not update when other events bubble up

---

packages/vue-output-target/package-lock.json
packages/vue-output-target/package.json

Bumps the Vue package version to match the latest release.

chore(vue): bump package version

---

packages/vue-output-target/vue-component-lib/utils.ts

Ionic Framework Vue components using `router-link` do not apply an `href` property which causes components to render `div` or `button` elements when they should render an `a`. 
Check if `router-link` and `navManager` are defined so this only applies to Ionic Framework components. If both are defined then add the `href` property to the element with the value of `router-link`.

fix(vue): pass router-link value to href to properly render clickable elements

---

.github/workflows/actions/publish-npm/action.yml
.github/workflows/dev-build.yml
.github/workflows/format.yml
.github/workflows/prod-build.yml

`pnpm-lock` was created with pnpm 9 so the workflows need to match that version.

chore(ci): update use pnpm 9

---

packages/example-project/next-app/src/app/Input/Input.tsx
packages/react-output-target/package.json
packages/react-output-target/src/react/ssr.tsx
pnpm-lock.yaml

This PR is an experimental enhancement to #445 which considers the light DOM when serializing Stencil components. We've experienced that a Stencil component may consider the light DOM for certain rendering conditions, e.g. add style properties or class names to a host component if the light DOM contains a certain slot.
You can use this dev build `@stencil/react-output-target@0.0.1-dev.11722646072.12d0ef0b` for testing purposes. Any feedback is much appreciated!

Next.js SSR Hydration with Children

---

packages/angular-output-target/package.json
packages/react-output-target/package.json

In order to release `@stencil/react-output-target` and `@stencil/angular-output-target` this patch bumps the package versions which reflect the following changes:
- #464
- #465
- #459

chore(react|angular): bump package versions

---

packages/example-project/component-library-angular/src/directives/proxies.ts
packages/example-project/component-library-vue/src/proxies.ts
packages/example-project/component-library/src/components.d.ts
packages/example-project/component-library/src/components/my-component/my-component.tsx
packages/example-project/component-library/src/components/my-component/readme.md
packages/example-project/next-app/src/app/page.tsx
packages/example-project/next-app/test/specs/test.e2e.mts
packages/react-output-target/package.json
packages/react-output-target/src/react/ssr.tsx
pnpm-lock.yaml

if a Stencil component has a property like `toggleStyle`, it would cause it to not being serialized correctly to `toggle-style` in the server rendered HTML code.
This patch decamelizes all properties.
I changed the `kidsNames` property to `kidName` as arrays can't be properly serialized in React.

fix(react): decamelize all component props

---

packages/react-output-target/package.json
packages/react-output-target/src/react-output-target/create-component-wrappers.test.ts
packages/react-output-target/src/react-output-target/create-stencil-react-components.ts
packages/react-output-target/src/react/create-component.ts
packages/react-output-target/src/react/ssr.tsx
pnpm-lock.yaml

When server side rendering SSR components, we currently de-camelize the property name which is a wrong assumption, given Stencil user give their properties arbitrary names, e.g. when the `attribute` property is used:
```ts
@Prop({ attribute: 'multi-line', reflect: true, mutable: true }) isMultiLine: boolean = false;
```
The patch makes the output target pass along the mapping for attributes that Stencil then uses later when it hydrates the component.
n/a

fix(react): use property mapping from component meta

---

packages/react-output-target/src/react-output-target/utils/string-utils.test.ts
packages/react-output-target/src/react-output-target/utils/string-utils.ts

Stencil event name start with underscore, react output target isn't generated properly
Issue URL:
- Stencil event name start with underscore, react output target generated properly
-
-

fix(react-output-target): event name alignment to underscore

---

packages/react-output-target/src/react/constants.ts

We supress the `slot` property from being applied to the hydrated component. This is problematic as users may want to verify whether there is an element with such component.
Propagate this attribute and serialize it.

fix(react): propagate slot property when hydrating

---

packages/example-project/component-library-angular/package.json

The "module" field in the package.json of the Angular example project points to the fesm5 build.
The "module" field in the package.json of the Angular example project points to the fesm2015 build, as described in https://esbuild.github.io/api/#main-fields.
Without it Angular will use the fesm5 build when it could have used fesm2015.
If a project is already using the "module"-build it should support es2015.
I found this issue while investigating why my Angular project, which uses standalone Stencil Angular output, was failing to tree shake unused components. To resolve it, I not only had to modify the module field but also set `"sideEffects": false` to enable tree shaking.

fix: module points to es2015-build

---

.github/workflows/dev-build.yml

original authored by @rwaskiewicz in #338
Our tech debt burndown job uses the `set-output` syntax. `set-output` was deprecated on 2022.10.11, in
favor of a new syntax - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. starting 2023.05.31, `set-output` is intended to be disabled.
GitHub Issue Number: N/A
this commit updates all workflows using the "old" output nomenclature to
use the newer variant.  applying this commit will allow the tech debt burndown to continue to function as
expected.

repo: use new output nomenclature for dev builds

---

packages/angular/package.json
packages/react/package.json
packages/vue/package.json

- `@stencil/angular-output-target` to `v0.9.1`
- `@stencil/react-output-target` to `v0.7.3`
- `@stencil/vue-output-target` to `v0.9.0`
- #493 (https://github.com/ionic-team/stencil-ds-output-targets/pull/468/commits/4ee8c6dac395205d286cb645360c03dd77307f41)
- #467 (https://github.com/ionic-team/stencil-ds-output-targets/commit/62f296504be5c006257e51c2d2792a43729f7272)
- #471 (https://github.com/ionic-team/stencil-ds-output-targets/commit/fa90560e48946ff872ee54461813e5df8b4b2026)
- #474 (https://github.com/ionic-team/stencil-ds-output-targets/commit/516f33476b968c5f48554c2f10be5fb31f4baaba)
- #484 (https://github.com/ionic-team/stencil-ds-output-targets/commit/199349c67a20e858bfb4c70a075133bd05f86640)
- #480 …

Publish: Angular, React and Vue output targets

---

packages/angular/package.json
packages/react/package.json

- `@stencil/angular-output-target` to `v0.10.0`
- `@stencil/react-output-target` to `v0.7.4`
- #508 (https://github.com/ionic-team/stencil-ds-output-targets/commit/a11a8d80d5e996fc59ebb7ab025a606660a9a3ca)
- #514 (https://github.com/ionic-team/stencil-ds-output-targets/commit/11470780a1f02e970a405eb4b229cda0ee1e8270)
- #497 (https://github.com/ionic-team/stencil-ds-output-targets/commit/756a4665f49723e6bccf962f01ceaf54eae99bdf)

Publish: @stencil/angular-output-target v0.10.0, @stencil/react-output-target v0.7.4

---

packages/react/package.json

The package.json does not explicitly define a Node.js-specific entry point. As a result, consumers of the package in Node.js environments rely on the default entry point, which may lead to incorrect module resolution or format issues when used in Node.js.
Add a node-specific entry point for the React package. This ensures that the correct module format is used when the package is required in a Node.js environment.

feat: Add a node-specific entry point for the React package

---

example-project/component-library-angular/src/directives/proxies.ts
packages/angular/src/generate-angular-component.ts
packages/angular/tests/generate-angular-component.test.ts

When using the new `inlineProperties` configuration option, properties only update correctly when they are used unbounded(`<my-component prop="value" />`), on the angular side. Bound(`<my-component [prop]="componentProperty" />`) properties are not synced correctly.
Properties work correctly, no matter if they are used bound or unbounded.
PR #497 by @kristilw introduced a long awaited fix for Angular, allowing the Angular Language Server to pick up the types of inputs correctly.
The change works correctly on the Typescript side, as well as at runtime, if the input properties are unbound. However, if they are bound the Angular Compiler does _something_ that prevents the binding …

fix(angular): 2-way data-binding for inlined Inputs

---

packages/react/src/react/ssr.tsx

Issue URL: #561 
see Issue
None.

fix: further resolve type of async components

---

example-project/component-library-vue/__tests__/my-component.spec.ts
example-project/component-library-vue/package.json
example-project/component-library-vue/src/index.ts
example-project/component-library-vue/vitest.config.ts
example-project/nuxt-app/test/specs/test.e2e.ts
example-project/vue-app/tests/test.e2e.ts
packages/vue/src/generate-vue-component.test.ts
packages/vue/src/generate-vue-component.ts
packages/vue/src/runtime.ts
pnpm-lock.yaml

-  [x] Tests for the changes have been added (for bug fixes / features)
- Event do not emit in Vue on many common components.
```
// will never fire!
function myChange(e) {
console.log("custom event change !") 
}
<MyComponent @myChange="myChange" />
```
Issue URL:
https://github.com/ionic-team/stencil-ds-output-targets/issues/382
- You can now handler on a custom event on a Vue component. 
```
// will never fire!
function myChange(e) {
console.log("custom event change !") 
}
<MyComponent @myChange="myChange" />
```

fix(vue): emits events on runtime

---

packages/angular/package.json
packages/react/package.json
packages/vue/package.json

- `@stencil/angular-output-target` to `v0.10.1`
- `@stencil/react-output-target` to `v0.8.0`
- #540 (https://github.com/ionic-team/stencil-ds-output-targets/commit/528ba3abd80ae0b47877af5d0ed11c88b50ebe48)
- #549 (https://github.com/ionic-team/stencil-ds-output-targets/commit/aa405fab2763316a471b5f997eab31aa1be73d0a)
- #562 (https://github.com/ionic-team/stencil-ds-output-targets/commit/1b8fb076daef56fcd54034936d2f6bc17c53cda0)
- #543 (https://github.com/ionic-team/stencil-ds-output-targets/commit/e9c6056c276a3a4a924585dae86458311187d4f3)
- #533 (https://github.com/ionic-team/stencil-ds-output-targets/commit/61a3975d9111dadf5f6dab0553c71693fb912577)
- #566 (https://github.com/ionic-team/stencil-ds-output-targets/commit/1a …

Publish: @stencil/angular-output-target v0.10.1, @stencil/react-output-target v0.8.0, @stencil/vue-output-target v0.9.1

---

packages/react/src/react/ssr.tsx

There are cases where we can't resolve the children of React components during the SSR process. In most cases this can be ignored as Next.js properly resolves the children individually. Right now we print the warning to stdout which may confuse folks when running e.g. tests with Playwright.
Disable the logging and put it behind a flag.
n/a

fix(react): hide SSR rendering error

---

example-project/component-library-react/package.json
example-project/component-library-vue/src/index.ts
example-project/next-app/package.json
example-project/nuxt-app/package.json
example-project/vue-app/package.json
packages/react/package.json
packages/vue/package.json
packages/vue/src/output-vue.test.ts
packages/vue/src/output-vue.ts
pnpm-lock.yaml

In Vue the output target would generate a file importing the JSX namespace from `/components`, e.g.
```ts
import type { JSX } from 'component-library/components';
```
This works when using the old Node classic import resolution but fails with ESM and Node16 and up.
Since the the default export just re-exports what's in `/components`, e.g. `export * from './components';` we can just adjust the import path.

fix(vue): import JSX from default component library export

---

example-project/component-library-angular/src/directives/proxies.ts
example-project/component-library-react/src/components.ts
example-project/component-library-vue/src/index.ts
example-project/component-library/src/components.d.ts
example-project/component-library/src/components/my-list-item/my-list-item.tsx
example-project/component-library/src/components/my-list-item/readme.md
example-project/component-library/src/components/my-list/my-list.tsx
example-project/component-library/src/components/my-list/readme.md
example-project/component-library/src/components/my-toggle-content/my-toggle-content.tsx
example-project/component-library/src/components/my-toggle-content/readme.md
example-project/component-library/src/components/my-toggle/my-toggle.tsx
example-project/component-library/src/components/my-toggle/readme.md
example-project/next-app/src/app/LazyComponent/LazyComponent.tsx
example-project/next-app/src/app/LazyComponent/LazyLoadedComponent.tsx
example-project/next-app/src/app/List/List.tsx
example-project/next-app/src/app/PureReactComponent/PureReactComponent.tsx
example-project/next-app/src/app/ThemeContext/ThemeContext.tsx
example-project/next-app/src/app/ToggleableContent/ToggleableContent.tsx
example-project/next-app/src/app/components.server.ts
example-project/next-app/src/app/components.ts
example-project/next-app/src/app/dsd/[component]/page.tsx
example-project/next-app/src/app/layout.tsx
example-project/next-app/src/app/page.tsx
example-project/next-app/test/specs/__snapshots__/dsd.e2e.mts.snap
example-project/next-app/test/specs/dsd.e2e.mts
example-project/next-app/test/specs/test.e2e.mts
packages/react/src/react/ssr.tsx

There are still some cases where resolving the correct types fails, which results in warnings and, occasionally, incorrectly rendered content.
Issue URL: #561 
Resolve component types correctly also for nested and lazy components.
I’ve added some new components and new tests to the Next.js example project to verify that the generated HTML includes the expected Declarative Shadow DOM.

fix(react): improve resolving component types

---

packages/react/package.json

- `@stencil/react-output-target` to `v0.8.2`
- https://github.com/ionic-team/stencil-ds-output-targets/pull/594
- https://github.com/ionic-team/stencil-ds-output-targets/pull/583

Publish: @stencil/react-output-target v0.8.2

---

packages/vue/package.json

- `@stencil/vue-output-target` to `v0.9.3`
- https://github.com/ionic-team/stencil-ds-output-targets/pull/606

Publish: @stencil/vue-output-target v0.9.3

---

CHANGELOG.md
packages/vue/package.json

- `vue-output-target`
- [#617](https://github.com/ionic-team/stencil-ds-output-targets/pull/617) Fix vue output target ([@andrewbeng89](https://github.com/andrewbeng89))

Publish: @stencil/vue-output-target v0.9.5

---

example-project/component-library-angular/projects/library/src/directives/proxies.ts
packages/angular/src/generate-angular-component.ts
packages/angular/src/output-angular.ts
packages/angular/tests/generate-angular-component.test.ts
packages/angular/tests/output-angular.test.ts

This commit implements a fix for bug:#643, providing IDE support for Angular component outputs
* Add `outputs` property to the component decorator
* Generate correct event emitter types matching interface declarations
* Genarate the outputs array internally from the events parameter
* Update 15 test cases to match the new format
- Generated Angular components only include an inputs property in the @Component decorator, but no outputs property
- IDE tools like IntelliSense cannot properly recognize or autocomplete component outputs/events
- The createAngularComponentDefinition function requires both outputs and events parameters, containing duplicate information about the same …

fix(angular): include outputs in angular component definition
